"""Export the fsd stack as per-output-channel symmetric int8 (SIMD-padded).

Layout per quantized conv (all rows padded to n16 = ceil(in_ch/16)*16):
  w8   int8 [out_ch][n16]
  scale f32 [out_ch]     (weight scale, max|row|/127)
  bias  f32 [out_ch]
Float-kept params: depthwise convs, GroupNorm gamma/beta, block scales.

Writes golden/model_q8.bin + golden/fsd_q8_meta.h (byte offsets).
Run from repo root: .venv/bin/python esp32c3/fsd/export_fsd_q8.py
"""

import json
import pathlib
import sys

pathlib.WindowsPath = pathlib.PosixPath

import numpy as np
import torch

REPO = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tools"))

import importlib.util

spec = importlib.util.spec_from_file_location(
    "dm", REPO / "tools/train_roota_piper_decoder_student.py"
)
dm = importlib.util.module_from_spec(spec)
sys.modules["dm"] = dm
spec.loader.exec_module(dm)

CHECKPOINT = (
    REPO
    / "artifacts/sub10m-search/root-a-piper-vits"
    / "en_US-kristin-u600-r7-14k-20260703/joint-14k-step-60000/decoder-student.pt"
)
OUT = pathlib.Path(__file__).resolve().parent / "golden"
KEYS = {
    "in_channels", "channels", "res_layers", "variant", "rank_ratio", "activation",
    "post_filter_channels", "post_filter_layers", "post_filter_kernel",
    "post_filter_scale", "istft_n_fft", "fsd_dim", "fsd_blocks", "fsd_film_rank",
    "fsd_head_rank", "stage_projection_bottlenecks",
}


def n16(x: int) -> int:
    return (x + 15) // 16 * 16


def main() -> None:
    ck = torch.load(CHECKPOINT, map_location="cpu", weights_only=False)
    cfg = {k: v for k, v in ck["config"].items() if k in KEYS}
    dec = dm.DecoderStudent(**cfg)
    dec.load_state_dict(ck["model_state_dict"], strict=True)
    enc = dm.LrcEncoder(in_channels=192, hidden=64, code_dim=40)
    enc.load_state_dict(ck["lrc_encoder_state_dict"], strict=True)

    blob = bytearray()
    offsets: dict[str, int] = {}
    meta: dict[str, int] = {}

    def align(k: int) -> None:
        while len(blob) % k:
            blob.append(0)

    def add_q8(name: str, w: torch.Tensor, b: torch.Tensor) -> None:
        """w: [out, in] float -> int8 rows padded to n16(in)."""
        wf = w.detach().float().numpy()
        out_ch, in_ch = wf.shape
        pad = n16(in_ch)
        scales = np.abs(wf).max(axis=1) / 127.0
        scales[scales == 0.0] = 1.0
        q = np.clip(np.round(wf / scales[:, None]), -127, 127).astype(np.int8)
        qp = np.zeros((out_ch, pad), dtype=np.int8)
        qp[:, :in_ch] = q
        align(16)
        offsets[f"{name}_w8"] = len(blob)
        blob.extend(qp.tobytes())
        align(4)
        offsets[f"{name}_scale"] = len(blob)
        blob.extend(scales.astype("<f4").tobytes())
        offsets[f"{name}_bias"] = len(blob)
        blob.extend(b.detach().float().numpy().astype("<f4").tobytes())
        meta[f"{name.upper()}_N16"] = pad

    def add_f32(name: str, t: torch.Tensor) -> None:
        align(4)
        offsets[f"{name}_f32"] = len(blob)
        blob.extend(t.detach().float().contiguous().numpy().astype("<f4").tobytes())

    add_q8("enc0", enc.net[0].weight.squeeze(-1), enc.net[0].bias)
    add_q8("enc1", enc.net[2].weight.squeeze(-1), enc.net[2].bias)
    add_q8("pre", dec.pre.weight.squeeze(-1), dec.pre.bias)
    for i, blk in enumerate(dec.fsd_blocks):
        add_f32(f"b{i}_dw_w", blk.depthwise.weight.squeeze(1))
        add_f32(f"b{i}_dw_b", blk.depthwise.bias)
        add_f32(f"b{i}_norm_w", blk.norm.weight)
        add_f32(f"b{i}_norm_b", blk.norm.bias)
        add_q8(f"b{i}_filmr", blk.film_reduce.weight.squeeze(-1), blk.film_reduce.bias)
        add_q8(f"b{i}_filmo", blk.film_out.weight.squeeze(-1), blk.film_out.bias)
        add_q8(f"b{i}_pw0", blk.pointwise0.weight.squeeze(-1), blk.pointwise0.bias)
        add_q8(f"b{i}_pw1", blk.pointwise1.weight.squeeze(-1), blk.pointwise1.bias)
        add_f32(f"b{i}_scale", blk.scale.reshape(1))
    add_q8("head_in", dec.fsd_head_in.weight.squeeze(-1), dec.fsd_head_in.bias)
    add_q8("head_out", dec.fsd_head_out.weight.squeeze(-1), dec.fsd_head_out.bias)

    (OUT / "model_q8.bin").write_bytes(bytes(blob))
    lines = ["/* generated by export_fsd_q8.py -- byte offsets into model_q8.bin */",
             "#pragma once", ""]
    for key, value in meta.items():
        lines.append(f"#define Q8_{key} {value}")
    lines.append("")
    for name, off in offsets.items():
        lines.append(f"#define Q8OFF_{name.upper()} {off}")
    lines.append(f"\n#define Q8_MODEL_BYTES {len(blob)}")
    (OUT / "fsd_q8_meta.h").write_text("\n".join(lines) + "\n")
    print(json.dumps({"model_q8_bytes": len(blob)}))


if __name__ == "__main__":
    main()
